spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      #实时更新数据库表结构
    show-sql: true
      #控制台显示sql语句
#设置日志
logging:
  level:
    root: warn
    #日志输出滤过级别
    com.jijuwuhua: info
  file: log/blog.log
    #日志存放目录

